pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/AndrexeBeta/esp32-cronoface.git'
            }
        }

        stage('Install PlatformIO') {
            steps {
                bat 'pip install platformio'
            }
        }

        stage('Compile Firmware') {
            steps {
                dir('Cronoface') {        // carpeta donde está platformio.ini
                    bat 'pio run'
                }
            }
        }
    }
}
